# Generated by Django 4.1 on 2022-08-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_parent_alter_colors_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
