# Generated by Django 4.1 on 2022-08-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_productincart_color_remove_productincart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='product_color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.colors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productincart',
            name='product_size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.sizes'),
            preserve_default=False,
        ),
    ]
