# Generated by Django 4.1 on 2022-08-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productincart_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
