# Generated by Django 4.1 on 2022-08-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='made_order',
            field=models.BooleanField(default=False),
        ),
    ]
